title: vue3-poc
description: Learning Lab 検証用コース
template:
  repo: vue3-poc-template
  name: vue3-poc
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
    store:
      first_issue_url: '{{ result.data.html_url }}'
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ store.first_issue_url }}'
    actions:
      - type: respond
        with: next-issue.md